portainer:
  image: portainer/portainer
  restart: always
  environment:
    - "VIRTUAL_HOST=portainer.*"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
docker-vhosts:
  image: texthtml/docker-vhosts
  restart: always
  environment:
    - "VIRTUAL_HOST=workbench.*"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"